import {COLORS, LIGHTER_COLORS} from './colors';

export const enum POKEMON_TYPES {
  bug = 'bug',
  dark = 'dark',
  dragon = 'dragon',
  electric = 'electric',
  fairy = 'fairy',
  fire = 'fire',
  fighting = 'fighting',
  flying = 'flying',
  ghost = 'ghost',
  grass = 'grass',
  ground = 'ground',
  ice = 'ice',
  normal = 'normal',
  poison = 'poison',
  psychic = 'psychic',
  rock = 'rock',
  steel = 'steel',
  water = 'water',
}

export const COLOR_BY_TYPE = {
  bug: COLORS.pistachioGreen,
  dark: COLORS.tobaccoBrown,
  dragon: COLORS.purplishBlue,
  electric: COLORS.brightGold,
  fairy: COLORS.dullPink,
  fire: COLORS.cadmiumOrange,
  fighting: COLORS.persianRead,
  flying: COLORS.palePurple,
  ghost: COLORS.mutedPurple,
  grass: COLORS.appleGreen,
  ground: COLORS.gingerBrown,
  ice: COLORS.pearlAqua,
  normal: COLORS.greenSmoke,
  poison: COLORS.warmPurple,
  psychic: COLORS.warmPink,
  rock: COLORS.brass,
  steel: COLORS.casper,
  water: COLORS.softBlue,
};

export const LIGHT_COLOR_BY_TYPE = {
  bug: LIGHTER_COLORS.pistachioGreen,
  dark: LIGHTER_COLORS.tobaccoBrown,
  dragon: LIGHTER_COLORS.purplishBlue,
  electric: LIGHTER_COLORS.brightGold,
  fairy: LIGHTER_COLORS.dullPink,
  fire: LIGHTER_COLORS.cadmiumOrange,
  fighting: LIGHTER_COLORS.persianRead,
  flying: LIGHTER_COLORS.palePurple,
  ghost: LIGHTER_COLORS.mutedPurple,
  grass: LIGHTER_COLORS.appleGreen,
  ground: LIGHTER_COLORS.gingerBrown,
  ice: LIGHTER_COLORS.pearlAqua,
  normal: LIGHTER_COLORS.greenSmoke,
  poison: LIGHTER_COLORS.warmPurple,
  psychic: LIGHTER_COLORS.warmPink,
  rock: LIGHTER_COLORS.brass,
  steel: LIGHTER_COLORS.casper,
  water: LIGHTER_COLORS.softBlue,
};
